/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ModuleSchema extends BaseModel {
  static $columns = ['admin', 'createdAt', 'id', 'name'] as const
  $columns = ModuleSchema.$columns
  @column()
  declare admin: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
}

export class PasskeySchema extends BaseModel {
  static $columns = [
    'backedUp',
    'counter',
    'credId',
    'id',
    'publicKey',
    'transports',
    'userId',
    'webauthnUserId',
  ] as const
  $columns = PasskeySchema.$columns
  @column()
  declare backedUp: boolean
  @column()
  declare counter: bigint | number
  @column({ isPrimary: true })
  declare credId: number
  @column()
  declare id: string
  @column()
  declare publicKey: Buffer
  @column()
  declare transports: string
  @column()
  declare userId: number
  @column()
  declare webauthnUserId: string
}

export class PermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'doubleAuth', 'id', 'key', 'name', 'type', 'updatedAt'] as const
  $columns = PermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare doubleAuth: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column()
  declare name: string
  @column()
  declare type: 'read' | 'create' | 'update' | 'delete' | 'revoke' | 'run'

  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'givenNames',
    'id',
    'lastNames',
    'password',
    'requiresPasskeyLogin',
    'super',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare givenNames: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastNames: string | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare requiresPasskeyLogin: boolean
  @column()
  declare super: boolean | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
